"""remove extra fields

Revision ID: 530be9c0c874
Revises: a6a2d98fd352
Create Date: 2024-05-10 16:30:24.876051

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '530be9c0c874'
down_revision = 'a6a2d98fd352'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'following_count')
    op.drop_column('User', 'follower_count')
    op.drop_column('User', 'phone')
    op.drop_column('User', 'state')
    op.drop_column('User', 'birthdate')
    op.drop_column('User', 'gender')
    op.drop_column('User', 'country')
    op.drop_column('User', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('gender', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('birthdate', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('follower_count', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('following_count', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
