"""added limit models

Revision ID: 03514d1eb0b2
Revises: eed182c62cde
Create Date: 2024-05-01 18:14:18.746329

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '03514d1eb0b2'
down_revision = 'eed182c62cde'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Limits',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('daily_swipe_limit', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('daily_match_limit', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('daily_conversations_limit', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('daily_messages_limit', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Limits_id'), 'Limits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Limits_id'), table_name='Limits')
    op.drop_table('Limits')
    # ### end Alembic commands ###
