"""added chatting settings models

Revision ID: 20f27778d054
Revises: 10e35ea5ef67
Create Date: 2024-05-01 18:27:13.558651

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '20f27778d054'
down_revision = '10e35ea5ef67'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChattingSettings',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('target_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_cta', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('messages_before_handle', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('begin_chatting_every', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('no_old_conversations_messages', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ChattingSettings_id'), 'ChattingSettings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ChattingSettings_id'), table_name='ChattingSettings')
    op.drop_table('ChattingSettings')
    # ### end Alembic commands ###
