"""added delays models

Revision ID: 6b1832d1d005
Revises: 03514d1eb0b2
Create Date: 2024-05-01 18:23:10.554501

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '6b1832d1d005'
down_revision = '03514d1eb0b2'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Delays',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('response_delay', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('followup_delay', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('open_profile_delay', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('delay_before_message', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Delays_id'), 'Delays', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Delays_id'), table_name='Delays')
    op.drop_table('Delays')
    # ### end Alembic commands ###
