"""added general settings models

Revision ID: 2c43982bf5c1
Revises: 20f27778d054
Create Date: 2024-05-01 19:07:40.735068

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = '2c43982bf5c1'
down_revision = '20f27778d054'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm") 
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('GeneralSettings',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('block_images', sa.Boolean(), nullable=False),
    sa.Column('sleep_duration', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('random_naps', sa.BigInteger(), server_default='0', nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['Project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GeneralSettings_id'), 'GeneralSettings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_GeneralSettings_id'), table_name='GeneralSettings')
    op.drop_table('GeneralSettings')
    # ### end Alembic commands ###
